### ISSUE TITLE
unable to install with npm

### ISSUE THREAD

**Issue by mmcfall** [pgriess/node-webworker#26]
Installing with node v0.4.8, npm 1.0.15, centOS 5.5-64. Getting following error:

npm ERR! tar "-mvxpf" "-" "-o" "-C" "/tmp/npm-1310337053203/1310337053203-0.9732671466190368/contents/___package.npm" tar: Ignoring unknown extended header keyword `LIBARCHIVE.creationtime'
npm ERR! tar "-mvxpf" "-" "-o" "-C" "/tmp/npm-1310337053203/1310337053203-0.9732671466190368/contents/___package.npm" tar: Ignoring unknown extended header keyword`SCHILY.dev'
npm ERR! tar "-mvxpf" "-" "-o" "-C" "/tmp/npm-1310337053203/1310337053203-0.9732671466190368/contents/___package.npm" tar: Ignoring unknown extended header keyword `SCHILY.ino'
npm ERR! tar "-mvxpf" "-" "-o" "-C" "/tmp/npm-1310337053203/1310337053203-0.9732671466190368/contents/___package.npm" tar: Ignoring unknown extended header keyword`SCHILY.nlink'

and then it repeats until:

npm ERR! tar "-mvxpf" "-" "-o" "-C" "/tmp/npm-1310337053203/1310337053203-0.9732671466190368/contents/___package.npm" tar: Error exit delayed from previous errors
npm ERR! tar "-mvxpf" "-" "-o" "-C" "/tmp/npm-1310337053203/1310337053203-0.9732671466190368/contents/___package.npm" 
npm ERR! Failed unpacking /tmp/npm-1310337053203/1310337053203-0.9732671466190368/tmp.tgz
npm ERR! couldn't unpack /tmp/npm-1310337053203/1310337053203-0.9732671466190368/tmp.tgz to /tmp/npm-1310337053203/1310337053203-0.9732671466190368/contents
npm ERR! Error: Failed tar "-mvxpf" "-" "-o" "-C" "/tmp/npm-1310337053203/1310337053203-0.9732671466190368/contents/___package.npm"
npm ERR! exited with 2
npm ERR!     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/exec.js:85:8)
npm ERR!     at ChildProcess.emit (events.js:67:17)
npm ERR!     at ChildProcess.onexit (child_process.js:192:12)
npm ERR! Report this _entire_ log at:
npm ERR!     http://github.com/isaacs/npm/issues
npm ERR! or email it to:
npm ERR!     npm-@googlegroups.com
npm ERR! 
npm ERR! System Linux 2.6.18-194.11.3.el5
npm ERR! command "node" "/usr/local/bin/npm" "install" "websocket-client"
npm ERR! cwd /home/admin
npm ERR! node -v v0.4.8
npm ERR! npm -v 1.0.15
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/admin/npm-debug.log
npm not ok

Same thing happens when doing npm install websocket-client. Possibly related?

Michael

**Comment by yyfrankyy** [comment]
me too.same problem, node 0.4.10, npm 1.0.1rc9

**Comment by isaacs** [comment]
Update the version of tar on your system.
