### ISSUE TITLE
node-webworker and node 0.8.x

### ISSUE THREAD

**Issue by rgermano** [pgriess/node-webworker#42]
Hello

Are there any plans to get node-webworker running on node 0.8.x? I'm currently getting the following error on node 0.8.0 and  webworker 0.8.4. Is the cluster module a correct replacement for webworkers? Thanks!

/Users/rgermano/node_modules/webworker/lib/webworker.js:35
var netBinding = process.binding('net');
                         ^
Error: No such module
    at Object.<anonymous> (/Users/rgermano/node_modules/webworker/lib/webworker.js:35:26)
    at Module._compile (module.js:449:26)
    at Object.Module._extensions..js (module.js:467:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:362:17)
    at require (module.js:378:17)
    at Object.<anonymous> (/Users/rgermano/iG/workspaces/cms/git/iGCMS_EdicaoHomes/lib/publicacao/controle.js:10:14)
    at Module._compile (module.js:449:26)
    at Object.Module._extensions..js (module.js:467:10)

**Comment by mikeatlas** [comment]
It looks like `netBinding` isn't used anyways.

**Comment by rgerard** [comment]
+1. I'm also having this issue.

**Comment by Nishchal** [comment]
Better to use Child processes spawned using the require('child-process') rather than the node-webworker implementation, since there are some changes on the latest node. So I think unless the node-webworker is updated it would be wise to use either the "fork, spawn" methods to do the work.

**Comment by adambom** [comment]
+1
