### ISSUE TITLE
Cannot use relative filenames when creating workers (e.g. ./child.js)

### ISSUE THREAD

**Issue by pgriess** [pgriess/node-webworker#9]
Witness:

```
Error: ENOENT, No such file or directory '/child.js'
    at Object.openSync (fs:150:18)
    at Object.readFileSync (fs:94:15)
    at Object.<anonymous> (/opt/local/lib/node/webworker/webworker-child.js:138:12)
    at Module._compile (node.js:472:25)
    at Module._loadScriptSync (node.js:482:10)
    at Module.loadSync (node.js:352:12)
    at Object.runMain (node.js:535:24)
    at node.js:760:10
```

**Comment by deepblue-phoenix** [comment]
+1

**Comment by EmilStenstrom** [comment]
+1

**Comment by pgriess** [comment]
Duplicate of #11.

If you can come up w/ a fix, I'd be happy to include it.
